vich_uploader:
    db_driver: orm

    mappings:
        quizzes:
            uri_prefix: /images/quizzes
            upload_destination: '%kernel.project_dir%/public/images/quizzes'
            inject_on_load: true
        questions :
            uri_prefix : /images/questions
            upload_destination: '%kernel.project_dir%/public/images/questions'
            inject_on_load: true
        themes :
            uri_prefix: /images/themes
            upload_destination: '%kernel.project_dir%/public/images/themes'
            inject_on_load: true
