vich_uploader:
    db_driver: orm

    mappings:
        quizzes:
            uri_prefix: /images/quizzes
            upload_destination: '%kernel.project_dir%/public/images/quizzes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        questions :
            uri_prefix : /images/questions
            upload_destination: '%kernel.project_dir%/public/images/questions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
